### ISSUE TITLE
New Netspace plans bug... (uploads not counted)

### ISSUE THREAD

**Issue by lombers** [chucknthem/Simple-Usage-Meter#11]
Hi,

This usage meter is great, except it doesn't work for the newer netspace plans which count uploads for monthly data. I believe this may be a simple issue with the scrape, can you please have a look at this?

I can provide you with the netspace usage page source if this helps. 

Regards

David

**Comment by chucknthem** [comment]
Hi David, 

I'll take a look. If you don't mind, can you visit this page https://USERNAME:PASSWORD@usage.netspace.net.au/usage-meter/adslusage?version=3&granularity=MONTH
as well as
https://USERNAME:PASSWORD@usage.netspace.net.au/usage-meter/adslusage?version=4&granularity=MONTH

and go to view source on your browser and email the xml to simpleusage@cmalabs.com? The usage meter uses that page to fetch netspace usage, I'll need an example of a plan that counts uploads to see what I need to do 

Cheers,

Charles

**Comment by chucknthem** [comment]
btw, replace USERNAME and PASSWORD with your netspace login.

**Comment by lombers** [comment]
Hi Charles,

I have sent you the source of these pages via email.

Thanks for your quick response. 

Regards

David

**Comment by chucknthem** [comment]
Thanks for that! Updated to 0.6.5 with a fix :)
