### ISSUE TITLE
add support for apex internet

### ISSUE THREAD

**Issue by kizmetau** [chucknthem/Simple-Usage-Meter#9]
Can you please add support for apex internet. It's simple XML all documented at http://forums.whirlpool.net.au/forum-replies.cfm?t=1417069

Thanks,
Kiz'Au

**Comment by chucknthem** [comment]
Thanks for the link! Added in version 0.6.3, the login is untested since I don't have an apex account, so if you could help install and test it that would be awesome, thanks :)

**Comment by kizmetau** [comment]
Doesn't work :(
Displays about 15 repetitions of:

undefined
NaN%
Quota   undefined/undefined
Remaining   NaN GB (NaN%)
NaN GB per day
Target Surplus  NaN GB (NaNd)
Time Remaining  11 hrs
Last Update 0 minutes ago

You can use: apimetertest / apimetertest to test your code :)

Thanks
Kiz'Au

**Comment by kizmetau** [comment]
Reopen, Whoops.

**Comment by chucknthem** [comment]
Thanks for the feedback Kiz'Au, what's apimetertest?

**Comment by Drex** [comment]
Hi Chuck,  I have tried this out, and kizmetau is right.  I get exactly the same results from Apex (long scrollbar, with lots of repetitions of undefined in pretty much all fields).  apimetertest is a test login/password to test the usage meter function.  I just tried it out and it returns data in the prescribed format (although not in Simple Usage Meter).

Many thanks,

Drex

**Comment by chucknthem** [comment]
Thanks Drex, updated to version 0.6.4, try it out and let me know if it works!

**Comment by kizmetau** [comment]
Works now! Thanks.

**Comment by Drex** [comment]
Sorry, thought I had posted here.  It works perfectly now - many thanks

**Comment by kizmetau** [comment]
Hi Chuck,

New functionality of the Apex API allow's passing the ISP generated graphs through the API. Would you be interested in allowing this kind of image display in the usage meter?

The details are all on the Whirlpool link previously provided.

**Comment by chucknthem** [comment]
Thanks for the update mate, I'm pretty busy atm to work on simple usage, but i'll look into it when i have time in a months time.
